const places = [
  {
    name: "Pithla Bhakri",
    category: "food",
    subCategory: "local food",
    description: "Traditional Maharashtrian dish made from gram flour and served with bhakri.",
    location: null,
    best_places: ["Sadhana Restaurant"],
    timings: null,
    price_range: "₹₹",
    speciality: null,
    popular_dish: null,
    distance: null,
    best_time: null,
    entry_fee: null,
    services: null,
    contact_number: null,
    rating: 4.6
  },
  {
    name: "Brew Bakes Cafe",
    category: "food",
    subCategory: "cafe",
    description: "Trendy cafe offering bakery items, coffee, and pizzas.",
    location: { address: "Gangapur Road, Nashik", lat: 19.965, lng: 73.720 },
    best_places: null,
    timings: "10:00 AM - 11:00 PM",
    price_range: "₹₹",
    speciality: "Bakery & Coffee",
    popular_dish: null,
    distance_from_city_km: null,
    best_time: null,
    entry_fee: null,
    services: null,
    contact_number: null,
    rating: 4.3
  },
  {
    name: "Chaat Bazaar Nashik",
    category: "food",
    subCategory: "street food",
    description: "Street-style chaat including pani puri, bhel, and sev puri.",
    location: { address: "College Road, Nashik", lat: 19.995, lng: 73.780 },
    best_places: null,
    timings: "5:00 PM - 10:30 PM",
 
    popular_dish: "Pani Puri",
    distance_from_city_km: null,
   
    contact_number: null,
    rating: 4.2
  },
  {
    name: "Gangapur Dam",
    category: "natural",
    subCategory: "dam",
    description: "One of the largest dams in Nashik, popular for sunset views and boating.",
    location: { address: "Gangapur, Nashik", lat: 19.950, lng: 73.700 },
    best_places: null,
    timings: "Open all day",
    price_range: null,
    speciality: null,
    popular_dish: null,
    distance_from_city_km: 10,
    best_time: "Monsoon, Evening",
    entry_fee: "Free",
    services: null,
    contact_number: null,
    rating: null
  },
  {
    name: "Anjaneri Hills Viewpoint",
    category: "natural",
    subCategory: "viewpoint",
    description: "Scenic hill offering panoramic views of Nashik and surrounding forests.",
    location: { address: "Anjaneri, Nashik", lat: 19.932, lng: 73.700 },
    best_places: null,
    timings: "6 AM - 6 PM",
    price_range: null,
    speciality: null,
    popular_dish: null,
    distance_from_city_km: 17,
    best_time: "Monsoon, Winter",
    entry_fee: "Free",
    services: null,
    contact_number: null,
    rating: null
  },
  {
    name: "Sula Vineyards",
    category: "wine",
    subCategory: "winery",
    description: "India’s most famous winery offering vineyard tours, wine tasting, and resort stay.",
    location: { address: "Gangapur-Savargaon Road, Nashik", lat: 19.963, lng: 73.712 },
    best_places: null,
    timings: "11:00 AM - 10:00 PM",
    price_range: null,
    speciality: "Wine Tasting",
    popular_dish: null,
    distance_from_city_km: 15,
    best_time: null,
    entry_fee: "₹600–₹1000",
    services: ["Wine Tasting", "Guided Tours", "Restaurant", "Stay"],
    contact_number: "+912536622000",
    rating: 4.6
  }
];