[
  {
    "name": "Anjaneri Hills Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Anjaneri Hills Viewpoint is a scenic destination near Trimbakeshwar, known for its breathtaking panoramic views of Nashik city, surrounding forests, and the Sahyadri mountain ranges. It is a popular spot for trekkers, photographers, and nature lovers seeking peaceful sunrise, sunset, and fresh mountain air experiences.",
    "location": "Anjaneri, Trimbakeshwar Taluka, Nashik District, Maharashtra, India",
    "distance": 17,
    "bestTime": "Monsoon, Winter",
    "timings": "6 AM - 6 PM",
    "entry_fee": "Free"
  },
  {
    "name": "Brahmagiri Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Brahmagiri Viewpoint is a stunning mountain destination near Trimbak, offering mesmerizing sunrise views, deep valleys, and lush green hill landscapes. It is a favorite among adventure seekers, spiritual travelers, and photographers looking to enjoy the natural beauty of the Western Ghats.",
    "location": "Brahmagiri Hills, Trimbak, Nashik District, Maharashtra, India",
    "distance": 30,
    "bestTime": "Monsoon",
    "timings": "6 AM - 6 PM",
    "entry_fee": "Free"
  },
  {
    "name": "Harihar Base Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Harihar Base Viewpoint offers beautiful scenic views of green valleys, farmlands, and surrounding mountain landscapes at the base of the famous Harihar Fort. It is a peaceful destination for visitors who want to enjoy nature, photography, and the dramatic beauty of the Sahyadri region.",
    "location": "Nirgudpada Village, Trimbakeshwar Taluka, Nashik District, Maharashtra, India",
    "distance": 40,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Igatpuri Mountain Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Igatpuri Mountain Viewpoint is one of the most scenic destinations near Nashik, famous for mist-covered hills, waterfalls, railway valley views, and refreshing weather. It attracts road trippers, nature enthusiasts, and photographers, especially during the monsoon season.",
    "location": "Igatpuri, Nashik District, Maharashtra, India",
    "distance": 45,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Camel Valley Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Camel Valley Viewpoint is a famous scenic destination near Igatpuri, known for its dramatic cliffs, waterfalls, deep valleys, and breathtaking monsoon landscapes. It is one of the best spots for enjoying cloud-covered mountain views and nature photography.",
    "location": "Igatpuri Ghat, Nashik District, Maharashtra, India",
    "distance": 50,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Ashoka Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Ashoka Viewpoint is a picturesque highway viewpoint offering stunning valley scenery, green mountain landscapes, and cool breezes throughout the year. It is a popular quick stop for travelers and photography lovers exploring the Kasara-Igatpuri route.",
    "location": "Kasara Ghat, Nashik District, Maharashtra, India",
    "distance": 55,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Bhatsa River Valley Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Bhatsa River Valley Viewpoint offers panoramic views of the river valley surrounded by rolling hills, greenery, and peaceful natural landscapes. It is a relaxing destination for nature lovers seeking scenic drives, photography, and quiet outdoor experiences.",
    "location": "Near Igatpuri, Nashik District, Maharashtra, India",
    "distance": 48,
    "bestTime": "Monsoon, Winter",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Vaitarna Lake Viewpoint",
    "category": "place to visit",
    "subcategory": "dam",
    "description": "Vaitarna Lake Viewpoint is a beautiful nature destination surrounded by mountains, calm waters, and peaceful landscapes. It is ideal for photography, scenic drives, picnics, and visitors who enjoy serene lakeside views away from crowded tourist spots.",
    "location": "Vaitarna Lake, Igatpuri, Nashik District, Maharashtra, India",
    "distance": 60,
    "bestTime": "Monsoon, Winter",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Gangapur Dam Viewpoint",
    "category": "place to visit",
    "subcategory": "dam",
    "description": "Gangapur Dam Viewpoint is a popular scenic destination in Nashik, known for peaceful water views, colorful sunsets, and a relaxing atmosphere. It is a favorite evening hangout spot for families, couples, and photography enthusiasts.",
    "location": "Gangapur Dam, Nashik, Maharashtra, India",
    "distance": 10,
    "bestTime": "Evening, Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Darna Dam Viewpoint",
    "category": "place to visit",
    "subcategory": "dam",
    "description": "Darna Dam Viewpoint offers scenic views of a large reservoir surrounded by hills, greenery, and peaceful open spaces. It is a great destination for monsoon drives, nature photography, and relaxing outdoor visits with family or friends.",
    "location": "Darna Dam, Igatpuri, Nashik District, Maharashtra, India",
    "distance": 50,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Valdevi Dam Viewpoint",
    "category": "place to visit",
    "subcategory": "dam",
    "description": "Valdevi Dam Viewpoint is a lesser-known scenic destination near Nashik, ideal for visitors looking for peaceful water views, quiet natural surroundings, and less crowded picnic spots. It is especially beautiful during the monsoon season.",
    "location": "Valdevi Dam, Nashik, Maharashtra, India",
    "distance": 12,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Someshwar Waterfall",
    "category": "place to visit",
    "subcategory": "Waterfall",
    "description": "Someshwar Waterfall is a seasonal natural attraction near Nashik, known for its flowing waters, lush surroundings, and relaxing picnic atmosphere. It is a popular family-friendly destination during monsoon and a favorite among local visitors.",
    "location": "Someshwar, Nashik, Maharashtra, India",
    "distance": 8,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Dugarwadi Waterfall",
    "category": "place to visit",
    "subcategory": "Waterfall",
    "description": "Dugarwadi Waterfall is a hidden forest waterfall near Nashik, offering a refreshing escape into nature with lush greenery, trekking trails, and scenic surroundings. It is especially popular during monsoon among adventure lovers and waterfall explorers.",
    "location": "Dugarwadi, Peth Road, Nashik District, Maharashtra, India",
    "distance": 65,
    "bestTime": "Monsoon",
    "timings": "8 AM - 5 PM",
    "entry_fee": "₹20 approx"
  },
  {
    "name": "Vihigaon Waterfall",
    "category": "place to visit",
    "subcategory": "Waterfall",
    "description": "Vihigaon Waterfall is a famous adventure destination near Igatpuri, known for its powerful waterfall, scenic surroundings, and exciting rappelling activities. It is a must-visit monsoon spot for thrill seekers and outdoor enthusiasts.",
    "location": "Vihigaon, Nashik District, Maharashtra, India",
    "distance": 60,
    "bestTime": "Monsoon",
    "timings": "8 AM - 5 PM",
    "entry_fee": "₹50 approx"
  },
  {
    "name": "Ashoka Hilltop",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Ashoka Hilltop is a scenic elevated destination offering spectacular 360-degree views of valleys, mountain ghats, and surrounding landscapes. It is a peaceful place for sightseeing, short road trips, and photography lovers.",
    "location": "Kasara Ghat, Nashik District, Maharashtra, India",
    "distance": 55,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Trimbak Forest Viewpoint",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Trimbak Forest Viewpoint is a peaceful natural destination surrounded by dense greenery, fresh mountain air, and scenic forest landscapes. It is perfect for visitors seeking quiet nature escapes, photography, and relaxing drives near Trimbakeshwar.",
    "location": "Trimbak, Nashik District, Maharashtra, India",
    "distance": 28,
    "bestTime": "Monsoon, Winter",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Saputara Border Valley View",
    "category": "place to visit",
    "subcategory": "Viewpoint",
    "description": "Saputara Border Valley View is a scenic mountain viewpoint near the Maharashtra-Gujarat border, known for expansive valley views, cool weather, and beautiful monsoon landscapes. It is ideal for road trips, sightseeing, and nature photography.",
    "location": "Saputara Road, Nashik District, Maharashtra, India",
    "distance": 120,
    "bestTime": "Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  },
  {
    "name": "Bhandardara Backwater View",
    "category": "place to visit",
    "subcategory": "Lake",
    "description": "Bhandardara Backwater View offers stunning lake and mountain scenery with peaceful surroundings, making it a perfect destination for camping, photography, and nature escapes. It is especially beautiful during monsoon and winter with misty landscapes.",
    "location": "Near Bhandardara, Igatpuri Region, Maharashtra, India",
    "distance": 70,
    "bestTime": "Winter, Monsoon",
    "timings": "Open all day",
    "entry_fee": "Free"
  }
]