[
  {
    name: "Sula Vineyards",
    category: "wine",
    subCategory: "Wineries",
    description:
      "India’s most iconic and widely recognized winery, Sula Vineyards offers a complete vineyard tourism experience including guided vineyard walks, wine production tours, premium wine tasting sessions, fine dining restaurants, luxury resort accommodation, and scenic views of rolling vineyards. It is one of the top attractions in Nashik for wine lovers and leisure travelers.",
    location: "Gangapur-Savargaon Road, Nashik",
    distance: 15,
    timings: "11:00 AM - 10:00 PM",
    entry_fee: "₹600–₹1000 (tour + tasting)",
    contact_number: "+912536622000",
    services: ["Wine Tasting", "Guided Tours", "Restaurant", "Stay"],
    rating: 4.6,
  },
  {
    name: "York Winery",
    category: "wine",
    subCategory: "Wineries",
    description:
      "A boutique winery located near Gangapur Dam, York Winery is known for its premium handcrafted wines, peaceful vineyard atmosphere, and beautiful lake views. Visitors can enjoy relaxed wine tasting experiences, gourmet dining, and a calm escape away from the city, making it ideal for couples and wine enthusiasts.",
    location: "Gangapur Dam, Nashik",
    distance: 14,
    timings: "12:00 PM - 8:00 PM",
    entry_fee: "₹300–₹500",
    contact_number: "+919970001234",
    services: ["Wine Tasting", "Restaurant", "Lake View"],
    rating: 4.4,
  },
  {
    name: "Soma Vine Village",
    category: "wine",
    subCategory: "Wineries",
    description:
      "A premium vineyard resort combining luxury hospitality with wine tourism, Soma Vine Village offers elegant stay options, vineyard tours, curated wine tasting experiences, swimming pool access, and fine dining. It is a perfect destination for weekend getaways, romantic stays, and luxury wine experiences in Nashik.",
    location: "Gangapur Dam, Nashik",
    distance: 13,
    timings: "10:00 AM - 10:00 PM",
    entry_fee: "₹500+",
    contact_number: "+919890123456",
    services: ["Wine Tasting", "Stay", "Pool", "Restaurant"],
    rating: 4.5,
  },
  {
    name: "Grover Zampa Vineyards",
    category: "wine",
    subCategory: "Wineries",
    description:
      "A well-known premium winery recognized for producing export-quality wines, Grover Zampa offers informative guided tours explaining the complete wine-making journey from grape cultivation to fermentation, aging, and bottling. It is a great destination for visitors interested in learning about professional wine production.",
    location: "Sanjegaon, Nashik",
    distance: 25,
    timings: "10:00 AM - 6:00 PM",
    entry_fee: "₹500 approx",
    contact_number: "+912536622345",
    services: ["Wine Tours", "Wine Tasting"],
    rating: 4.3,
  },
  {
    name: "Vallonne Vineyards",
    category: "wine",
    subCategory: "Wineries",
    description:
      "A charming French-inspired boutique vineyard known for its intimate wine experiences, Vallonne Vineyards offers premium tasting sessions, vineyard tours, elegant architecture, and a peaceful countryside atmosphere. It is ideal for travelers seeking a sophisticated and less crowded winery experience.",
    location: "Sanjori, Nashik",
    distance: 22,
    timings: "11:00 AM - 7:00 PM",
    entry_fee: "₹400–₹700",
    contact_number: "+919823456789",
    services: ["Wine Tasting", "Guided Tours"],
    rating: 4.4,
  },
  {
    name: "Sula Vineyard Tour Experience",
    category: "wine",
    subCategory: "Wine Tours",
    description:
      "A guided educational vineyard tour where visitors can walk through grape plantations, understand the wine-making process in detail, explore the production facility and cellars, and conclude with a curated tasting session led by experienced wine guides. One of the most popular wine tourism experiences in Nashik.",
    location: "Sula Vineyards, Nashik",
    distance: 15,
    timings: "Multiple slots (11 AM - 6 PM)",
    entry_fee: "₹600+",
    contact_number: "+912536622000",
    includes: ["Guide", "Wine tasting", "Cellar visit"],
    rating: 4.7,
  },
  {
    name: "Grover Zampa Wine Tour",
    category: "wine",
    subCategory: "Wine Tours",
    description:
      "An engaging educational wine tour that introduces visitors to grape cultivation, fermentation, storage, aging techniques, and bottling processes. The experience is designed for wine learners and enthusiasts who want a behind-the-scenes understanding of professional winery operations.",
    location: "Grover Zampa Vineyards, Nashik",
    distance: 25,
    timings: "10 AM - 5 PM",
    entry_fee: "₹500",
    contact_number: null,
    includes: ["Winery visit", "Wine tasting"],
    rating: 4.3,
  },
  {
    name: "Vallonne Wine Tour",
    category: "wine",
    subCategory: "Wine Tours",
    description:
      "A premium guided wine tour offering a relaxed walk through scenic vineyards along with expert explanations of grape varieties, wine crafting techniques, and tasting etiquette. Perfect for those seeking a refined boutique winery experience.",
    location: "Vallonne Vineyards, Nashik",
    distance: 22,
    timings: "11 AM - 6 PM",
    entry_fee: "₹500",
    contact_number: null,
    includes: ["Wine tasting", "Guided tour"],
    rating: 4.4,
  },
  {
    name: "Sula Wine Tasting Session",
    category: "wine",
    subCategory: "Wine Tasting",
    description:
      "A curated wine tasting experience featuring multiple premium wines served with expert guidance explaining aroma, flavor notes, tasting techniques, and pairing suggestions. Suitable for beginners as well as experienced wine enthusiasts.",
    location: "Sula Vineyards, Nashik",
    distance: 15,
    timings: "All day",
    entry_fee: "₹600–₹1000",
    contact_number: "+912536622000",
    includes: ["6 wine samples", "Guide"],
    rating: 4.7,
  },
  {
    name: "York Wine Tasting",
    category: "wine",
    subCategory: "Wine Tasting",
    description:
      "A peaceful and scenic wine tasting experience where visitors can sample premium wines while enjoying beautiful views of Gangapur Dam. The relaxed ambiance makes it ideal for casual wine lovers, couples, and weekend visitors.",
    location: "York Winery, Nashik",
    distance: 14,
    timings: "12 PM - 8 PM",
    entry_fee: "₹300–₹500",
    contact_number: null,
    includes: ["Wine tasting"],
    rating: 4.4,
  },
  {
    name: "Soma Wine Tasting",
    category: "wine",
    subCategory: "Wine Tasting",
    description:
      "A luxury wine tasting experience set within a premium vineyard resort atmosphere, allowing visitors to enjoy curated wine samples, elegant surroundings, and a relaxing upscale hospitality experience. Great for leisure travelers and special occasions.",
    location: "Soma Vine Village, Nashik",
    distance: 13,
    timings: "10 AM - 9 PM",
    entry_fee: "₹500+",
    contact_number: null,
    includes: ["Wine tasting", "Resort access"],
    rating: 4.5,
  }
]